---
title: "A synthesis of early cognitive and language development using (meta-)meta-analysis"
bibliography: library.bib
csl: apa6.csl
document-params: "10pt, letterpaper"

author-information: > 
    \author{Anjie Cao$^1$  (anjiecao@stanford.edu), 
     Molley Lewis (mollylewis@gmail.com), \\
     and \bf{Michael C. Frank$^1$ (mcfrank@stanford.edu)} \\
    $^1$Department of Psychology, Stanford University
    }

abstract: >
  Young children acquire a wide range of linguistic and cognitive skills in the first three years of life. Decades of experimental work have established a solid empirical foundation for our understanding of cognitive development. But most experimental studies are limited in statistical power and focus on specific psychological constructs, thus making them unsuitable for describing developmental growth at scale. Here, we turned to meta-analyses of experimental research. We conducted a meta-meta-analysis to consolidate and integrate 23 meta-analyses compiled on MetaLab, a community-augmented meta-analysis platform. We found that most datasets can not meaningfully distinguish different functional forms for developmental change, but in those that could, there is great diversity in the best-fitting functional forms of the age model. We also evaluated the impact of a range of methodological factors. Overall, our work sheds light on the heterogeneous nature of developmental trajectories and the subtle interactions between research methods and experimental outcomes. 


    
keywords: >
    meta-analysis; cognitive development; language learning

    
output: 
    cogsci2016::cogsci_paper
    
  
nocite: | 
  

header-includes   :


final-submission: \cogscifinalcopy
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=3, fig.height=3, fig.crop = F, 
                      fig.pos = "tb", fig.path='figs/',
                      echo=F, warning=F, cache=F, 
                      message=F, sanitize = T)
```


```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(metafor)
library(kableExtra)
library(patchwork)


d <- read_csv(here("data/clean_data.csv"))
author_d <- read_csv(here("data/clean_author.csv"))


source(here("helper/plot_moderator_help.r"))

# Summary 
summary_df <- readRDS(here("cached_data/summary_d.Rds"))


# Functional form eval
age_df <- readRDS(here("cached_data/age_models_df.Rds"))

# cached methodological moderators 
best_fit_bmeasure_model_df <- readRDS(here("cached_data/best_fit_behavioral_measure_df.Rds"))
best_fit_bmeasure_interaction_df <- readRDS(here("cached_data/best_fit_behavioral_measure_interaction_df.Rds"))


best_fit_exposure_phase_df <- readRDS(here("cached_data/best_fit_exposure_phase.Rds"))
best_fit_real_visual_df <- readRDS(here("cached_data/best_fit_real_visual_df.Rds"))
best_fit_real_aud_df <- readRDS(here("cached_data/best_fit_real_aud_df.Rds"))
best_fit_major_author_df <- readRDS(here("cached_data/best_fit_major_author_df.Rds"))

# preiction curve
all_age_pred <- readRDS(here("cached_data/min_age_pred_df.RDS"))

# i2
i2_df <- readRDS(here("cached_data/i2_df.Rds"))
```



# Introduction 


```{r child = "01_introduction.Rmd"}
```


# Methods  


```{r child = "02_methods.Rmd"}
```

# Results  

```{r child = "03_results.Rmd"}
```


# Discussion  

```{r child = "04_discussion.Rmd"}
```


# References 

\setlength{\parindent}{-0.1in} 
\setlength{\leftskip}{0.125in}
\noindent
